### ISSUE TITLE
为什么选用 typhoeus 作为 http 组件呢

### ISSUE THREAD

**Issue by yiichou** [ohimy/qcloud-sms#1]
RT
请求的返回是一个 Typhoeus::Response 对象，Gem 本身并没有对返回结果做处理
这也就是说，要比较好的使用这个插件还需要去看一下 Typhoeus 的文档

感觉使用 Net::HTTP 是不是也挺合适的

**Comment by ohimy** [comment]
Typhoeus是对libcurl的直接封装，效率高于Net::HTTP，使用上也要方便点。

**Comment by yiichou** [comment]
嗯 确实是一个挺有意思的 gem ，可以指定 cache ，还可以 .and_return(response)
不过这样的话，建议对请求结果做封装，返回一个 Qcloud::SmsResponse  对象吧，如此使用者就不会感受到 Typhoeus 的存在了，对普通使用者更友好

当然也可以留个口子，让使用者可以直接获得 Typhoeus 的返回，给需要定制开发的使用者提供便利

**Comment by ohimy** [comment]
空了来改进一下，感谢建议
